# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geoinfo', '0004_auto_20171211_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u59d3\u540d')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='\u7f16\u53f7')),
                ('gen', models.CharField(blank=True, choices=[('male', '\u7537'), ('female', '\u5973')], max_length=30, verbose_name='\u6027\u522b')),
                ('PDA', models.CharField(blank=True, max_length=100, verbose_name='PDA\u53f7\u7801')),
                ('head', models.CharField(blank=True, max_length=300, verbose_name='\u5934\u50cf')),
            ],
        ),
        migrations.CreateModel(
            name='InspectorGrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='\u76d1\u7763\u5458\u7ec4')),
            ],
        ),
        migrations.AddField(
            model_name='inspector',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.InspectorGrop', verbose_name='\u4ece\u5c5e\u7ec4'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='scope',
            field=models.ManyToManyField(blank=True, to='geoinfo.BlockPolygon', verbose_name='\u5de5\u4f5c\u533a\u57df'),
        ),
    ]
