# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-11 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.InspectorGrop', verbose_name='\u4ece\u5c5e\u7ec4'),
        ),
    ]
