# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-11 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0002_auto_20171211_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='group',
        ),
        migrations.AddField(
            model_name='inspectorgrop',
            name='insp',
            field=models.ManyToManyField(blank=True, null=True, to='inspector.Inspector', verbose_name='\u76d1\u7763\u5458'),
        ),
    ]
