# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-18 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0004_auto_20171211_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='last_loc',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u4e0a\u6b21\u5750\u6807'),
        ),
        migrations.AddField(
            model_name='inspector',
            name='track_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8ffd\u8e2a\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='inspectorgrop',
            name='inspector',
            field=models.ManyToManyField(blank=True, to='inspector.Inspector', verbose_name='\u76d1\u7763\u5458'),
        ),
    ]
