# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-02 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0005_auto_20171218_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='\u7f16\u53f7')),
                ('page', models.TextField(blank=True, verbose_name='\u6848\u5b50\u9875\u9762')),
            ],
        ),
    ]
