# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-02 08:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0006_inspectorcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorcase',
            name='update_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 2, 8, 43, 31, 513000, tzinfo=utc), verbose_name='\u66f4\u65b0\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
