# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-27 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0007_inspectorcase_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='scope',
        ),
    ]
