# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0008_remove_inspector_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectorWorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='监督员组')),
                ('work_time', models.CharField(blank=True, help_text='8:00-12:00;13:30-17:30', max_length=300, verbose_name='监督员组')),
                ('inspector', models.ManyToManyField(blank=True, to='inspector.Inspector', verbose_name='监督员')),
            ],
        ),
    ]
