# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0010_auto_20180701_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectorgrop',
            name='kind',
            field=models.IntegerField(choices=[(0, '缺省'), (1, '围栏'), (2, '排班')], default=0, verbose_name='类型'),
        ),
    ]
