# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-17 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0011_inspectorgrop_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectorgrop',
            options={'verbose_name': '监督员分组表'},
        ),
        migrations.AlterField(
            model_name='inspectorgrop',
            name='name',
            field=models.CharField(error_messages={'unique': '相同名字的组已经存在，请换一个名字'}, max_length=100, unique=True, verbose_name='组名'),
        ),
        migrations.AlterField(
            model_name='inspectorworkgroup',
            name='name',
            field=models.CharField(error_messages={'unique': '相同名字的组已经存在，请换一个名字'}, max_length=100, unique=True, verbose_name='组名'),
        ),
        migrations.AlterField(
            model_name='inspectorworkgroup',
            name='work_time',
            field=models.CharField(help_text='(8:00-12:00;13:30-17:30)<br>按照括号内的格式输入，以分号分割时间段', max_length=300, verbose_name='工作时间段'),
        ),
    ]
