# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-18 17:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import helpers.director.model_func.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuchaCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(blank=True, max_length=20, verbose_name='\u4efb\u52a1\u53f7')),
                ('subtime', models.CharField(blank=True, max_length=20, verbose_name='\u53d1\u73b0\u65f6\u95f4')),
                ('bigclass', models.CharField(blank=True, max_length=30, verbose_name='\u5927\u7c7b')),
                ('litclass', models.CharField(blank=True, max_length=30, verbose_name='\u5c0f\u7c7b')),
                ('addr', models.CharField(blank=True, max_length=500, verbose_name='\u5730\u5740')),
                ('pic', helpers.director.model_func.jsonfield.JsonField(blank=True, verbose_name='\u56fe\u7247')),
                ('audio', helpers.director.model_func.jsonfield.JsonField(blank=True, verbose_name='\u97f3\u9891')),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='\u7ecf\u7eac\u5ea6')),
            ],
        ),
    ]
