# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-04 18:10
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspector', '0013_auto_20180802_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuchaCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(blank=True, max_length=20, verbose_name='任务号')),
                ('subtime', models.CharField(blank=True, max_length=20, verbose_name='发现时间')),
                ('bigclass', models.CharField(blank=True, max_length=30, verbose_name='大类')),
                ('litclass', models.CharField(blank=True, max_length=30, verbose_name='小类')),
                ('addr', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('pic', models.TextField(blank=True, verbose_name='图片')),
                ('audio', models.TextField(blank=True, verbose_name='音频')),
                ('KEY', models.CharField(blank=True, max_length=30, verbose_name='KEY')),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='经纬度')),
            ],
        ),
        migrations.CreateModel(
            name='JianduCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskid', models.CharField(blank=True, max_length=20, verbose_name='任务号')),
                ('subtime', models.CharField(blank=True, max_length=20, verbose_name='发现时间')),
                ('bigclass', models.CharField(blank=True, max_length=60, verbose_name='大类')),
                ('litclass', models.CharField(blank=True, max_length=60, verbose_name='小类')),
                ('addr', models.CharField(blank=True, max_length=500, verbose_name='地址')),
                ('loc', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='经纬度')),
                ('org_code', models.TextField(blank=True, verbose_name='原始抓取数据')),
                ('infotypeid', models.IntegerField(help_text='0:部件，1：事件')),
                ('status', models.IntegerField(help_text='5:待受理;9:结案;10:已作废')),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('deptcode', models.CharField(help_text='赵巷：20601', max_length=10, verbose_name='主责部门')),
                ('executedeptcode', models.CharField(blank=True, help_text='赵巷：20601', max_length=20, verbose_name='三级主责部门')),
                ('keepersn', models.ForeignKey(blank=True, db_column='keepersn', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.Inspector', to_field='code')),
            ],
        ),
    ]
