# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-19 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_cmp', '0002_jianducase'),
    ]

    operations = [
        migrations.AddField(
            model_name='duchacase',
            name='KEY',
            field=models.CharField(blank=True, max_length=30, verbose_name='KEY'),
        ),
    ]
