# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-01 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_cmp', '0003_duchacase_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duchacase',
            name='audio',
            field=models.TextField(blank=True, verbose_name='\u97f3\u9891'),
        ),
        migrations.AlterField(
            model_name='duchacase',
            name='pic',
            field=models.TextField(blank=True, verbose_name='\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='jianducase',
            name='org_code',
            field=models.TextField(blank=True, verbose_name='\u539f\u59cb\u6293\u53d6\u6570\u636e'),
        ),
    ]
