# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-02 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_cmp', '0006_auto_20180717_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jianducase',
            name='bigclass',
            field=models.CharField(blank=True, max_length=60, verbose_name='大类'),
        ),
        migrations.AlterField(
            model_name='jianducase',
            name='keepersn',
            field=models.ForeignKey(blank=True, db_column='keepersn', db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspector.Inspector', to_field='code'),
        ),
        migrations.AlterField(
            model_name='jianducase',
            name='litclass',
            field=models.CharField(blank=True, max_length=60, verbose_name='小类'),
        ),
    ]
