# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-26 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockgroup',
            name='belong',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u5c5e\u4e8e'),
        ),
    ]
