# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-05 02:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockpolygon',
            name='bounding',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='\u63a2\u6d4b\u591a\u8fb9\u5f62'),
        ),
        migrations.AlterField(
            model_name='blockpolygon',
            name='display',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='\u663e\u793a\u591a\u8fb9\u5f62'),
        ),
    ]
