# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-12-11 04:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoinfo', '0003_auto_20171205_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockpolygon',
            name='label',
        ),
        migrations.AddField(
            model_name='blockpolygon',
            name='desp',
            field=models.TextField(blank=True, verbose_name='\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='blockpolygon',
            name='bounding',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='\u63a2\u6d4b\u591a\u8fb9\u5f62'),
        ),
        migrations.AlterField(
            model_name='blockpolygon',
            name='display',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='\u663e\u793a\u591a\u8fb9\u5f62'),
        ),
        migrations.AlterField(
            model_name='blockpolygon',
            name='name',
            field=models.CharField(max_length=300, verbose_name='\u540d\u5b57'),
        ),
    ]
