# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-08 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0008_remove_inspector_scope'),
        ('geoscope', '0002_blockgroup_belong'),
        ('dianzi_weilan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectorgroupandweilanrel',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='inspectorgroupandweilanrel',
            name='group',
        ),
        migrations.AddField(
            model_name='inspectorgroupandweilanrel',
            name='block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoscope.BlockPolygon', verbose_name='\u56f4\u680f\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='inspectorgroupandweilanrel',
            name='groups',
            field=models.ManyToManyField(null=True, to='inspector.InspectorGrop', verbose_name='\u5e94\u7528\u5bf9\u8c61'),
        ),
    ]
