# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-03-09 03:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0008_remove_inspector_scope'),
        ('geoscope', '0002_blockgroup_belong'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dianzi_weilan', '0002_auto_20180308_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutBlockWarning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u544a\u8b66\u65f6\u95f4')),
                ('proc_time', models.DateTimeField(auto_now=True, verbose_name='\u5904\u7406\u65f6\u95f4')),
                ('proc_status', models.CharField(choices=[('processed', '\u5df2\u5904\u7406'), ('unprocess', '\u672a\u5904\u7406')], max_length=30, verbose_name='\u5904\u7406\u72b6\u6001')),
                ('proc_detail', models.TextField(verbose_name='\u5904\u7406\u7ed3\u679c')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoscope.BlockPolygon', verbose_name='\u544a\u8b66\u533a\u57df')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspector.Inspector', verbose_name='\u76d1\u5bdf\u5458')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba\u5458')),
            ],
        ),
        migrations.AlterField(
            model_name='inspectorgroupandweilanrel',
            name='block',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoscope.BlockPolygon', verbose_name='\u56f4\u680f\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='inspectorgroupandweilanrel',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='inspector.InspectorGrop', verbose_name='\u5e94\u7528\u5bf9\u8c61'),
        ),
    ]
