# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 05:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dianzi_weilan', '0003_auto_20180309_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outblockwarning',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u5904\u7406\u4eba\u5458'),
        ),
        migrations.AlterField(
            model_name='outblockwarning',
            name='proc_detail',
            field=models.TextField(blank=True, verbose_name='\u5904\u7406\u7ed3\u679c'),
        ),
        migrations.AlterField(
            model_name='outblockwarning',
            name='proc_status',
            field=models.CharField(choices=[('processed', '\u5df2\u5904\u7406'), ('unprocess', '\u672a\u5904\u7406')], default='unprocess', max_length=30, verbose_name='\u5904\u7406\u72b6\u6001'),
        ),
    ]
