# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-10 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dianzi_weilan', '0004_auto_20180310_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outblockwarning',
            name='block',
        ),
    ]
