# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-28 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspector', '0008_remove_inspector_scope'),
        ('dianzi_weilan', '0005_remove_outblockwarning_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkInspector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='\u5bf9\u5e94\u65e5\u671f')),
                ('inspector', models.ManyToManyField(blank=True, to='inspector.Inspector', verbose_name='\u5bf9\u5e94\u76d1\u7763\u5458')),
            ],
        ),
    ]
