# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-04-09 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianzi_weilan', '0006_workinspector'),
    ]

    operations = [
        migrations.AddField(
            model_name='outblockwarning',
            name='reason',
            field=models.CharField(default='', max_length=700, verbose_name='\u8b66\u544a\u539f\u56e0'),
            preserve_default=False,
        ),
    ]
