# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianzi_weilan', '0007_outblockwarning_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outblockwarning',
            name='reason',
            field=models.CharField(blank=True, max_length=700, verbose_name='\u8b66\u544a\u539f\u56e0'),
        ),
    ]
