# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-27 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dianzi_weilan', '0008_auto_20180427_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinspector',
            name='date',
            field=models.DateField(null=True, verbose_name='对应日期'),
        ),
    ]
